### ISSUE TITLE
프론트엔드 폰트 설정

### ISSUE THREAD

**Issue by gyureal** [gyureal/studyOllePractice#19]
## 개요
- google font 에서 원하는 폰트를 가져오기
- 프로젝트 전역 폰트로 설정하기

## Details
- [google font](https://fonts.google.com/) 에서 원하는 폰트를 가져오기

korean <br/>
<img width="1123" alt="image" src="https://github.com/gyureal/studyOllePractice/assets/78974381/986eb72c-bfc3-4cb9-89b5-805b14fde42c">

font 추가 <br/>
<img width="1272" alt="image" src="https://github.com/gyureal/studyOllePractice/assets/78974381/c6685d8a-fe05-437c-999b-4171a490a104">

css link 를 head 에 추가한다.
<img width="301" alt="image" src="https://github.com/gyureal/studyOllePractice/assets/78974381/ec50b4b5-064b-46a2-912e-58f2a3343f8c">

<img width="869" alt="image" src="https://github.com/gyureal/studyOllePractice/assets/78974381/a9fb7806-7055-4beb-b70c-e81108cd70d6">

- 프로젝트에 폰트 적용하기
head에 아래 스타일을 추가해준다.  <br/>
<img width="763" alt="image" src="https://github.com/gyureal/studyOllePractice/assets/78974381/47c1edc9-ac3f-4ddf-abfe-a2a15ae8452b">

```css
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Noto Sans KR", "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        }

        body,
        input,
        button,
        select,
        optgroup,
        textarea,
        .tooltip,
        .popover {
            font-family: -apple-system, BlinkMacSystemFont, "Noto Sans KR", "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        }
```
